repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args: ["--fix=lf"]
    - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        name: "cargo clippy"
      - id: fmt
        name: "cargo fmt"
  - repo: https://github.com/bytewax/pre-commit-cbfmt
    rev: v0.1
    hooks:
      - id: fmt
        name: cbfmt
  - repo: https://github.com/netromdk/vermin
    rev: v1.5.2
    hooks:
      - id: vermin
        # Keep this Python version in sync with the `requires-python`
        # field in pyproject.toml. Add a `-` after the Python version
        # to say for `3.8-` "even if this code would work on 3.7,
        # that's fine".
        args: ["--eval-annotations", "--no-tips", "--violations", "-t=3.8-"]
